### ISSUE TITLE
Xcode 6 warning

### ISSUE THREAD

**Issue by danwalkowski** [RNCryptor/RNCryptor#138]
/Users/Dan/Development/xxxxxxx/Pods/RNCryptor/RNCryptor/RNOpenSSLCryptor.m:80:9: Incompatible pointer types assigning to 'NSMutableData *' from 'NSData *'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:103:1: Class method 'dataWithBytes:length:' is assumed to return an instance of its receiver type ('NSData *')

**Comment by rfunk82** [comment]
If you still using the old version just replace this line:

key = [NSData dataWithBytes:md length:sizeof(md)];

with:

key = [NSMutableData dataWithData:[NSData dataWithBytes:md length:sizeof(md)]];

**Comment by carllindberg** [comment]
That creates two NSData instances which is not necessary.  Just change to either:

key = [NSMutableData dataWithBytes:md length:sizeof(md)]];

or

return [NSData dataWithBytes:md length:sizeof(md)];

**Comment by DidierMalenfant** [comment]
I guess this isn't really maintained anymore?

**Comment by rnapier** [comment]
The OpenSSL code was moved to https://github.com/rnapier/RNOpenSSLCryptor.
It's not supported, but I would accept a CocoaPod if someone has a PR for
that. (You'll probably need a new xcodeproj.)

The main RNCryptor code is supported, but I don't do much with CocoaPods in
general. My thinking is I should actually tag a branch that just fixes this
warning so that CP users don't have to deal with all the major version
updates.

**Comment by DidierMalenfant** [comment]
Tagging a branch could work but it would still be good to tag the latest version too so that it's also accessible via cocoapods.

**Comment by levigroker** [comment]
+1 for continuing CocoaPod support (and fixing this warning).

**Comment by danwalkowski** [comment]
Ditto on CocoaPods support!
