### ISSUE TITLE
RNCryptor Inside a Framework

### ISSUE THREAD

**Issue by bassrock** [RNCryptor/RNCryptor#147]
When trying to use RNCryptor inside a framework I get this error:

```
Include of non-modular header inside framework module 'RNCryptor.RNCryptor'
```

Has anyone found a workaround?

**Comment by bbsan2k** [comment]
Currently Experiencing the same Issues with CocoaPods 0.3.6.rc.1
Is there any workaround?

**Comment by haaakon** [comment]
Having same problem. Anyone found out how to fix it?

**Comment by trondkr** [comment]
I am having the same issue and hoping to find a fix

**Comment by bassrock** [comment]
Any maintainers have an idea? I would use CryptoSwift instead, but at the moment it does not have the same speed.

**Comment by trondkr** [comment]
I managed to get this to work by changing "CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES" to Yes in "Build Settings". I found this solution on SO: http://stackoverflow.com/questions/24103169/swift-compiler-error-non-modular-header-inside-framework-module. What I don't know is if there is a catch to allowing this non modular framework modules.

**Comment by rnapier** [comment]
Try making the .h files public for the iOS build, rather than Project.
(right-hand pane, look for "Target Membership"). If that works, I'll push a
version that includes that.

I never use CocoaPods and am not particularly familiar with how it works. I
just include RNCryptor's files in my main project, and it generally is
fine. If someone has a PR for the podspec, I'm happy to merge it.

**Comment by bassrock** [comment]
@rnapier so the issue is that you can not include CommonCryptor in the Header file. I just created a pull request that should fix this by using the hard values instead of the constants.

**Comment by carllindberg** [comment]
@bassrock There must be a better solution than to use horrible magic constants everywhere in the code, and lose type-checking for enums.  CommonCrypto is a system framework and should be importable.  How does importing <Foundation/Foundation.h> work?

**Comment by bassrock** [comment]
It is importable. However you can not import it into a header file that will be public. So you have to at least make the base file the end values but could still pas it enums. Open to any other solutions but this is all I could make work.

**Comment by carllindberg** [comment]
So if you have a public header, you can't import any, say, Foundation or UIKit headers directly?   That seems like a rather silly restriction from Apple, counter to normal C usage.  At some point, there will be dependent third-party frameworks (i.e. ones which use constants, type names, or superclasses from another framework).  That is usually the type of thing which CocoaPods is supposed to make easy.

Does removing the imports (and just adding them to the .pch) work?  That would require all consumers to add the same imports to their .pch files (or at least right before they import RNCryptor wherever that is).  If that works, maybe there is a way in the precompile environment to figure out that a modular framework is being built, and to put the imports inside of some #if !BUILDING_FRAMEWORK checks or something like that.  But to me, using the named constants and types from CommonCrypto in the code should be an absolute must.

**Comment by bassrock** [comment]
So thats the catch. You can with Swift, but not with an iOS Framework that is written with Obj-C. The best solution would be to rewrite in Swift and then this would work.

As far as I could tell the modifications that I made were the only "easy" way for this to work, without having to use CocoaPods.

**Comment by carllindberg** [comment]
I edited my question above... does changing to <CommonCrypto/CommonCrypto.h> work (as opposed to the two individual imports)?

**Comment by bassrock** [comment]
Yea using the constants defineltly should be a priority, I just couldn't see how to do it. And when importing the catchall header it was the same issue because it ultimately ends up importing the other ones.

**Comment by carllindberg** [comment]
The errors sounds like importing UIKit/UIKit.h is OK because that's a module header, though UIKit/UIView.h individually might be a problem.   But if CommonCrypto is not a module (rather just a C library) then that sounds like an issue.

If CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES doesn't work, another short-term solution might be to do something like

#if !BUILDING_MODULE
#import <CommonCrypto/xxxx.h>
#elif !defined(_CC_COMMON_CRYPTOR_) // it wasn't imported some other way yet
// copy definitions from CommonCrypto since we can't import directly
enum {
    kCCEncrypt = 0, 
    kCCDecrypt,     
};
typedef uint32_t CCOperation;

(and so on)
#endif 

Then figure out some way to determine BUILDING_MODULE.  Could be a custom define in the framework target maybe.  That way the messiness is confined to one header, not every usage of the constants in the code.

**Comment by bassrock** [comment]
Well that is sort of the case I believe I only changed the constants in the header files. It still imports them and uses them in the .m files.

**Comment by carllindberg** [comment]
I guess the kRNCryptorAES256Settings constant could be declared extern const in the header (instead of static const), then defined in the .m file instead.  That would limit the extra goop needed to a handful of typedefs.  It is still beneficial to have the type names used in the structure -- it's part of the documentation of allowed values (not that anyone should be using a different structure in that case).

Seems odd that system headers can be included (it gets the definition of size_t somehow) but not CommonCrypto.  This may just be some growing pain issues with Swift and frameworks which Apple will find better solutions to eventually.

**Comment by rnapier** [comment]
I haven't been ignoring this conversation, btw, I just have been hoping
that a solution would present itself. I do believe it's transition pains
for Swift. I'd like to avoid removing the constants, since they're
important documentation. That said, I've long considered the need to
pass kRNCryptorAES256Settings a design flaw rather than a feature.
RNCryptor doesn't really expect you to make random changes to that struct.

I wonder if there's an easy way to fix this by providing a Swift interface
that does not expose the settings struct at all. Maybe split the Swift
interface into its own header and not import RNCryptor.h itself into Swift.

I have been very overloaded with other projects, and RNCryptor hasn't
gotten a lot of attention recently. I hope to change that, but I'm not
certain when. PRs are of course welcome and encouraged.

**Comment by rnapier** [comment]
Please help test the fix I've applied. I decided to go with something a little more radical than @bassrock's solution #149. Rather than swapping out the types, I copied all the types we need into a temporary header file. This should help a little with type safety (not much for ObjC, but maybe a little), documents better, and is very easy to pull out when CommonCrypto is fixed.

**Comment by lolgear** [comment]
is this issue fixed?
I have this issue at version 2.2
`Using RNCryptor (2.2)`

**Comment by rnapier** [comment]
Have you tested the commit I reference above? cb1036f I'm waiting for a confirmation that this fix works for other people before tagging it.

**Comment by lolgear** [comment]
@rnapier 

Yes

Information: I've implemented my security kit that based on apple's `CommonCryptor`.
```
#import "AIKSecurityKit.h"
#import <CommonCrypto/CommonHMAC.h>
#import <CommonCrypto/CommonCryptor.h>
#import <RNCryptor/RNEncryptor.h>
#import <RNCryptor/RNDecryptor.h>
```

I have these lines:

warnings:

`umbrella header for module 'RNCryptor' does not include header 'RNOpenSSLCryptor.h'`
`umbrella header for module 'RNCryptor' does not include header 'RNOpenSSLEncryptor.h'`
`umbrella header for module 'RNCryptor' does not include header 'RNOpenSSLCryptor.h'`

errors: (nearly nine or more, one error for each symbol from CommonCryptor )

```
MyProject/Security/SecurityKit/AIKSecurityKit.m:42:12: error: reference to 'kCCHmacAlgSHA256' is ambiguous
    CCHmac(kCCHmacAlgSHA256, cKey, strlen(cKey), cData, strlen(cData), cHMAC);
           ^
In module 'RNCryptor' imported from 
MyProject/Security/SecurityKit/AIKSecurityKit.m:13:
/Users/mac/Library/Developer/Xcode/DerivedData/SmartAirkey-himplrkcxiqdkzfpohykmuyhoqcd/Build/Products/Debug-iphonesimulator/RNCryptor.framework/Headers/RNCryptor+Swift.h:134:5: note: candidate found by name lookup is '::kCCHmacAlgSHA256'
    kCCHmacAlgSHA256,
    ^
In file included from 
MyProject//Security/SecurityKit/AIKSecurityKit.m:11:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/include/CommonCrypto/CommonHMAC.h:54:5: note: candidate found by name lookup is '::kCCHmacAlgSHA256'
    kCCHmacAlgSHA256,
```

**Comment by rnapier** [comment]
It looks like you have some mix of versions here. RNOpenSSLCryptor is not part of that cb1036f. It was removed for security concerns and put into its [own package](https://github.com/rnapier/RNOpenSSLCryptor). If you have something referencing those files, then it suggests you don't have a clean version of RNCryptor.

I suspect that AISecurityKit.h imports RNCryptor.h. That will likely cause problems if you later import CommonCryptor.h. You should import CommonCrypto first if you need it directly. (I assume this is an ObjC framework rather than a Swift framework.)

If that causes more trouble, then I'll have to drop the common crypto defines entirely and rename them all to internal constants. That's not a huge problem.

Do make sure you're not trying to link RNCryptor inside of another framework. That would be incredibly dangerous in cases that a consuming app uses RNCryptor for other purposes. Make sure that the final app links all the necessary frameworks (yours and anything you depend on). You should reference your headers from whatever version the app uses; they shouldn't be embedded either or you can get nasty surprises.

**Comment by lolgear** [comment]
@rnapier, well, you are right

I didn't make frameworks, AIKSecurityKit is a part of my app.
It has AIKSecurityKit which contains security related code like encoding/decoding ( SHA128/SHA256 and HMac )
I try to import RNCryptor into this kit and use it as a replacement
It works great for ObjC, but Swift migration/mix causes problems

I made clean install of pods and made build. 
Warnings disappeared.

Also, this import is a part of `AIKSecurityKit.m`
```
// AIKSecurityKit.m
#import "AIKSecurityKit.h"
#import <CommonCrypto/CommonHMAC.h>
#import <CommonCrypto/CommonCryptor.h>
#import <RNCryptor/RNEncryptor.h>
#import <RNCryptor/RNDecryptor.h>
```

**Comment by Nathan187** [comment]
Does anyone have a clean / concise method of getting RNCryptor to work within a Framework?  I'm using Cocoapods and I'm using frameworks.  Just setting the  CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES to Yes is not solving the problem.  I've been racking my head against the wall for a few hours on this.  

![rncryptor](https://cloud.githubusercontent.com/assets/1022238/9745919/3716ec9e-563a-11e5-9f20-2dafadc1f099.png)

**Comment by carllindberg** [comment]
It looks like that last commit undid the commit from #152.
