### ISSUE TITLE
Corrupted file for docx, pptx.  But work for doc, mp4, png.

### ISSUE THREAD

**Issue by Durgaprasad-kelkar** [RNCryptor/RNCryptor#168]
I am using this library to encrypt and decrypt files.

All other files except docx, pptx works fine. It use to work fine with old version 3.0. Issue came when I upgraded to swift file in 4.0

**Comment by Durgaprasad-kelkar** [comment]
Also getting this issue.
assertion failed: RNCRYPTOR BUG. PLEASE REPORT.: file /Users/durgaprasad/Developer/iosEncryption(synchronous)/iOS/insyncios/insyncios/Shared/RNCryptor.swift, line 598

**Comment by rnapier** [comment]
Do you have an example docx that demonstrates? So far I can't reproduce this using Word 2016.

**Comment by Durgaprasad-kelkar** [comment]
I made a mistake while calling finalData. File was not encrypting properly. 
Thanks for giving time to help me. Sorry I filed wrong bug. 

Anyway this sync library is great. Can you add async methods also.

**Comment by rnapier** [comment]
Can you send me an example of your mistake? Even if you did everything wrong, I did not expect that assertion to fire.

What would you particularly want in an async method? RNCryptor v3 had async methods, but I took them out because they made the calling code needlessly complicated. It's generally so easy to just wrap things in `dispatch_async`. But there may be use cases I haven't considered. (Can you open that as a separate issue, though? I don't want to track it as comments in a bug report.)
