### ISSUE TITLE
Using the same instance of RNCryptor.Encryptor more then once

### ISSUE THREAD

**Issue by rokgregoric** [RNCryptor/RNCryptor#171]
I am trying to encrypt an array of data in a loop and would like to use the same instance of the RNCryptor.Encryptor.

```swift
let encryptor = RNCryptor.Encryptor(password: password)

var encryptedArray = [NSData]()

for data in arrayToEncrypt {
  let encryptedData = encryptor.encryptData(data)
  encryptedArray.append(encryptedData)
}
```

I noticed that instantiating RNCryptor.Encryptor in a loop allocates a tons of NSData objects (super expensive and very slow).

I am not considering using `updateWithData` and `finalData` because I need every data object to be decrypt-able separately.

**Comment by rnapier** [comment]
Creating your `Encryptor` is expensive because you're using a password. That's on purpose. Converting a password into a key, by design, takes non-trivial time even on fast hardware.

The solution is not to use a password, but to use keys instead. See [Key Based Encryption](https://github.com/RNCryptor/RNCryptor#key-based-encryption).

If you need to use a password as the initial keying material, you can convert that into a pair of keys one time and reuse the keys in your loop. If that's the problem you're facing, I'll write up docs. If you can just generate two 32-byte random keys (they should be random in all their bits; not just a random 32-character string), that's better and faster. If you need help generating random keys in code, I can write that up. (RNCryptor includes that functionality already.)

If the array is large, this may still create a lot of autoreleased `NSData` objects. In order to keep the RNCryptor API simple, I chose to internally copy the data in some cases, and ARC may not immediately release those. For simple usage, you can just wrap your loop body in an autoreleasepool:

    for data in arrayToEncrypt {
        autoreleasepool {
            ...
        }
    }

That will make sure the excess `NSData` objects are cleaned up and don't push up your high-water mark more than necessary. This doesn't eliminate the copy and memory churn, however.

If you have a performance-critical situation, that would likely require some non-trivial enhancements to the RNCryptor API (or a new random-access format that I've discussed before to support video). I don't have any current plans to implement that, but if someone needs it, I'd be happy to discuss on a consulting basis.

**Comment by rokgregoric** [comment]
I would need to use a password .. so I would like to generate keys one time and reuse them. Can you help me with that?

**Comment by rnapier** [comment]
See the new Examples/KeyDerivation that should explain everything you need.
