### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by yjogol** [RNCryptor/RNCryptor#175]
Hi, 
if RNCryptor will be often instantiated it consumes lots of memory, or maybe I have done something wrong.
If you have for example a function for encrypting a file which create an instance of RNCryptor and then encrypt then this will lead to a memory problem. I have done this with an App and imported 20.000 files using more than 3GB RAM. Or is the design idea to instantiate RNCryptor only once?

Reproduction A, instantiate 100 times with 10MB Data takes >2GB RAM:

        let encryptKey = "000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f".dataFromHexEncoding!
        let hmacKey = "0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00".dataFromHexEncoding!
        let len = 1024*1024*10
        let data = RNCryptor.randomDataOfLength(len)

        for _ in 1...100 {
            let encryptor = RNCryptor.EncryptorV3(encryptionKey: encryptKey, hmacKey: hmacKey)
            let encrypted = encryptor.encryptData(data)
        }
Reproduction B, instantiate once - 30MB RAM in my test

        let encryptKey = "000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f".dataFromHexEncoding!
        let hmacKey = "0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00".dataFromHexEncoding!
        let len = 1024*1024*10
        let data = RNCryptor.randomDataOfLength(len)

        let encryptor = RNCryptor.EncryptorV3(encryptionKey: encryptKey, hmacKey: hmacKey)
        for _ in 1...100 {
            let encrypted = encryptor.encryptData(data)
        }

Thank you very much for your excellent work!
yjogol

**Comment by rnapier** [comment]
RNCryptor generates autoreleased data. If you call it in a loop, you need to let ARC know when to release that data. (Normally, ARC won't clean it up until the end of the event loop.)

Your loop should look like this:

    for _ in 1...100 {
        autoreleasepool {
            let encryptor = RNCryptor.EncryptorV3(encryptionKey: encryptKey, hmacKey: hmacKey)
            let encrypted = encryptor.encryptData(data)
        }
    }

Note the addition of `autoreleasepool`. At the end of the block, all autoreleased objects will be released.

You need to create a new encryptor for each separate stream of data (as in your first example). The second example should probably be causing an assert(), since it's undefined behavior. I'll think about adding that to prevent mistakes.

Using `encryptData()` to encrypt a 10MB file will take a total of 20MB of memory (which is where you're getting 2GB; 20MB*100). If that's still too much memory, remember that you can encrypt as you read from the file. See the "Incremental Usage" section of the README. That way you don't have to ever have the entire file in memory.
