### ISSUE TITLE
Timing Attack Vulnerabilities in Multiple Implementations

### ISSUE THREAD

**Issue by paragonie-scott** [RNCryptor/RNCryptor#183]
http://www.openwall.com/lists/oss-security/2016/01/24/10

**Comment by LookingSharp** [comment]
Are you saying the timing vulnerability exists in the swift version?  Looking at the code, I see isEqualInConsistentTime is used to compare data.  Does this vulnerability exist in this version?

**Comment by rnapier** [comment]
The ObjC and Swift implementations of RNCryptor (which are the primary implementations) do use constant-time hash comparisons. Have you found otherwise? The most common server side implementation is PHP, which also does constant-time hash comparisons (currently, though this took longer to get fixed then I liked).

I didn't write and don't directly support all the implementations, but please feel free to open issues on any implementations with this or any other error. RNCryptor defines a format. It has several implementations that various developers maintain. 

If you believe there is any defect in the Swift or ObjC implementations, I am happy to look at that here, but this repository doesn't cover all the independent implementations of the format. GitHub doesn't have any way to manage organization-level issues, so a separate issue is required on each repository. 

Thanks.

**Comment by paragonie-scott** [comment]
> Are you saying the timing vulnerability exists in the swift version?

No, I thought this was the main repo for the entire project.

**Comment by rnapier** [comment]
That's fine. But if you found specific implementations that had trouble, please let me know. I'm happy to open the issues myself. I'll go ahead and audit them all, but if you've already done some of it, that'll save me some time. 

Thanks for the notice.

**Comment by paragonie-scott** [comment]
https://github.com/RNCryptor/rncryptor-hs/blob/958630b09daad60d0115400c2e37cfdd9627ffa3/src/Crypto/RNCryptor/V3/Decrypt.hs#L110-L124

My Haskell kung-fu is weak; is this just discarding the MAC entirely?

**Comment by rnapier** [comment]
Yes. I believe it is discarding it.

**Comment by paragonie-scott** [comment]
I made a note in https://github.com/RNCryptor/rncryptor-hs/issues/2

**Comment by paragonie-scott** [comment]
OK, I think I found all the variable-time MAC validation flaws in the various implementations. I think there might be questionable choices w.r.t. the CSPRNG implementations on some of them, but until I research that in depth I don't feel comfortable raising the alarm.

Have fun.

**Comment by rnapier** [comment]
Thank you. Always glad to have extra eyes on these things.

**Comment by adinapoli** [comment]
@paragonie-scott @rnapier hey folks, made a note about HMAC validation here (happy to accept pointers):

https://github.com/RNCryptor/rncryptor-hs/issues/2
