### ISSUE TITLE
When to verify message with HMAC

### ISSUE THREAD

**Issue by LookingSharp** [RNCryptor/RNCryptor#185]
I've been having a discussion with a colleague about when HMAC should be verified.  I'm not a security expert, so after going back and forth on it a bit I thought I'd just pose it as an issue.  There are really two questions.

1) Should HMAC be verified before you start any decoding of the message?  There are tradeoffs especially when the cipher is very large.
2) In DecryptorEngineV3.finalData, should HMAC checking/throwing happen before engine.finalData() is called?  Is there a reason why it is ordered this way?

Thanks for your thoughts.

**Comment by rnapier** [comment]
Sorry for the long delay answering this.

Ideally the HMAC would be verified prior to decrypting any part of the message, but in practice this is too slow for general use. You'd have to spool everything into memory or disk before you could even begin to decrypt. (The next version of the data format does a better job of this by providing a password validator, but it still can't promise the data wasn't modified until the end of decryption.)

The security trade-off is two-fold: If there's a bug in RNCryptor itself (or CommonCryptor), the current scheme makes it slightly easier to exploit because the attacker can craft an arbitrary message. (In practice, though, it's hard to imagine a case where this would legitimately be an avenue of attack that pre-verifying would prevent.)

The second security problem, which is much easier to imagine and is the vector of several known exploits, would occur if the caller started processing the data before it was validated. Then, if the caller has bugs it may be possible to craft a message that exploits those. The caller can avoid this by not processing any data until finalData is completed. Managing this risk is best left to the caller, and RNCryptor doesn't try to fix it for you. (RNCryptor would basically have to remove the async interface to protect the caller, and that's a very high cost.)

Swapping the order in `DecryptorEngineV3.finalData` would probably be a fine change (and actually would make the code ever-so-slightly cleaner). It's difficult to imagine an exploit that would take advantage of the current order, but it's still worth doing.
