### ISSUE TITLE
Incremental usage across app restarts?

### ISSUE THREAD

**Issue by lemonkey-medhelp** [RNCryptor/RNCryptor#191]
Would the incremental usage outlined in the README be able to support appending onto an encrypted NSData object across multiple application sessions? E.g., writing encrypted data to a file, which is then appended to over time.

**Comment by rnapier** [comment]
No. When you created a new cryptor object, it would inject a new header (among other problems of remembering the new IV).

Rob

**Comment by lemonkey-medhelp** [comment]
What I suspected, thanks.

**Comment by lemonkey-medhelp** [comment]
I suppose you could read in the last 128 bits of an existing file (or stream for that matter) that was encrypted using AES-256 since the block size is consistent (and would be padded if the last appended block wasn't originally 128 bits in length) and use this as the IV when initializing a new cryptor object with the intention of appending.

However in the README you do mention that it is not intended for the IV to be set manually per the custom RNCryptor data format and other security issues.

Thoughts?

**Comment by rnapier** [comment]
You'd also have to read all the previous ciphertext to get the HMAC into the right state. And you wouldn't be able to decrypt and validate properly until the stream was finalized (to write the HMAC). It's certainly possible to build this, but it's not a good fit for the RNCryptor format. You'd want to build a different format for it, probably with HMACs computed over blocks rather than over the whole stream.

**Comment by lemonkey** [comment]
Got it. I have a working prototype that is just using CCCrypt and (kCCOptionPKCS7Padding | kCCModeCBC) for the options based on the iOS 7 pushing the limits book, but I'm going to evaluate supporting HMAC as well. Thanks again.
