### ISSUE TITLE
any technical reason why RNCryptor doesn't allow subclassing?

### ISSUE THREAD

**Issue by dautermann** [RNCryptor/RNCryptor#198]
[RNCryptor/RNCryptor.swift](RNCryptor/RNCryptor.swift) doesn't allow subclassing due to the `final` keyword for all the class definitions.

I'd love to subclass because the app I'm working on requires a somewhat different file format than RNCryptor (in order to be compatible with other architectures which don't get to use RNCryptor) and I'd like my subclass to be able to manipulate the data to & from that cross compiling format.  

I'm sure other RNCryptor users have wondered about this as well.  I realize I can update my local copy of RNCryptor to remove all the `final` keywords and build from that, but is there some technical reason why it was decided to declare all classes as `final`?  If it's a performance reason, [Swift 1.2 fixed things up](http://blog.human-friendly.com/the-importance-of-being-final).  Perhaps it's some other technical rationale?

**Comment by rnapier** [comment]
The classes in `RNCryptor` are final because they're not designed for subclassing. Allowing arbitrary subclasses is fragile if not documented and tested. If you need to look at my implementation in order to write your subclass, then you're relying on an implementation detail that may change. It's hard to imagine many subclasses that you could safely write purely from the API documentation. (This is one of the great mistakes that happened in OOP, which is one reason there is frequent discussion of making `final` the default in Swift and a general leaning towards structs.)


As a rule, I strongly recommend composition rather than inheritance. If at all possible, create a type of your own that HAS-A `RNCryptor` rather than IS-A `RNCryptor`. I'd be happy to discuss any specific problem you're facing.

A subclass of RNCryptor that modifies the format is also not an RNCryptor. That's just Liskov. A subclass must be substitutable in every place that the superclass is usable. If MYModifiedCryptor cannot accept the RNCryptor format as input, then it it's incorrect to make it a subclass. So any interesting subclass you made would likely have to be more complicated than you desire.

RNCryptor is already designed for composition. You'll note that the "RNCryptor-level" objects forward everything to "V3-level" objects. This is intentional. It is possible to create a new encryptor or decryptor that writes a different format and plug it into the RNCryptor wrapper. That's currently private but could potentially be made more public. (That said, I'm not certain how it would help very much unless you're trying to read both RNCryptor *and* other formats; in that case, it's built exactly to solve that problem.)

Note that `RNCryptor` is widely ported and is generally not that hard to implement. Is there a particular platform that would be helpful to have an implementation?

Can you explain the actual problem you're facing and what other format you're trying to write? I'm having trouble picturing what kind of format a subclass would be useful for. Perhaps you just want to use Engine. I intentionally pulled that out to make it easier to write more general-purpose formats.
