### ISSUE TITLE
Encryption/Decryption issue

### ISSUE THREAD

**Issue by AnkitGupta87** [RNCryptor/RNCryptor#211]
Lets say there is an app which downloads in background, encrypts and stores the file on disk, whenever the file is required by user it is decrypted and provided to the user.

Now following steps are performed:
1. put multiple files to download in background.
2. keep app on screen, lock the device.
3. let few files to get download.
4. update the app using Xcode in background, while download is still in progress.
5. now unlock the device
6. try using those files, any file which gets downloaded after device lock, faces some cryptography issue. But library doesn't gives any error.

Note: device lock has both pin / finger print enabled.
I am using version 4.0 of RNCryptor library.

**Comment by rnapier** [comment]
What do you mean by "faces some cryptography issue?" And what do you mean by "library doesn't gives any error?" How are you checking for error?

Did you verify that the file wrote successfully and was exactly what was originally encrypted?

The very likely problem is that you've truncated the data because the file was marked as data protection "Complete" rather than "UnlessOpen." But it's very hard to diagnose from the above information. I don't know how you're downloading in the background. Are you using NSURLSession's background download system?

But the main question is, what are "some cryptography issue?" What cryptography issue?

**Comment by AnkitGupta87** [comment]
- "faces some cryptography issue?" -> I am using media files which on download is encrypted and decrypted when it is to be used. After decryption it is not playing.
- For error I am relying on parameter provided to decryption method.
- Yes, both of them are verified. If I just remove the encryption everything works completely fine.
- After encryption of data I store it in a file and mark it with "UnlessOpen" protection.
- Yes, I am using NSURLSession's background download.

In the scenario I mentioned above if I don't update (kill) the app in locked device state. Then after unlocking the device all media files are playable and there is no issue at all. Is there something which on unlocking done to these files?

**Comment by rnapier** [comment]
If you do not receive an error during decryption, then you should verify that the decrypted bytes are the same as the original bytes. CommonCryptor definitely does not care whether the device is locked. You are almost certainly having a problem reading or writing files or accessing keychain. These are things that change when the device is locked.

**Comment by AnkitGupta87** [comment]
Thanks Rob for the clue on bytes, it seems to be some byte issue getting created. The library is not the cause.
