### ISSUE TITLE
Update master repo cocopods

### ISSUE THREAD

**Issue by alexs555** [RNCryptor/RNCryptor#217]
hello!
didn't u forget to update master repo of cocoapods?
4.0.0-beta.1 is the last version that I see in repo.
pod update causes installing of 4.0.0 release insted of 5.0.1

**Comment by shshalom** [comment]
I'm facing this issue as well.
My framework depends on RNCryptor, now that we've moved to swift 3 and with cocoapods still points to version 4.0.0 the only solution is to embed version 5.0.1 into the project.

please fix this issue.

**Comment by alexs555** [comment]
@shshalom you can in podfile set
pod 'RNCryptor', :git => 'https://github.com/RNCryptor/RNCryptor.git' and this will checkout master branch of 5.0.q version

**Comment by shshalom** [comment]
This solution doesn't works for me.

I'll try to explain why, so my project is an app which depends on another framework; that framework holds the entire server api logic, encryption and so on. natively RNCryptor sits inside the framework.

Now, the framework is used in private Cocoapod, Inside the podspec I've set RNCryptor as dependency,  since the master repo is set to download version 4.0.0, that's what get downloaded when using the framework.

Sadly I can't set the dependency as you suggested inside the podspec file.

One thought I had is, as an exception, to download RNCryptor, pointing to 5.0.1 branch inside the client app PodFile, which seemed to be a good solution, but on compiled it yield the following error:

> No such module 'RNCryptor' 

so that solution didn't work :-/

Another solution I had in mind, is to embed RNCryptor inside the project, but I'm struggling with the framework not recognizing  RNCryptor.h file (frameworks are not allowed to have bridging header)

So my only possible option I can think about right now is to get RNCryptor from Cocoapods with the latest version.

So that's my story, if you have another Idea in mind please let me know.

**Comment by alexs555** [comment]
Actually, we have the same situation as you described in 1 part. 
Our client app has in its podfile some private pods that have as a dependency RNCryptor. We added in client's pod file line 
 **pod 'RNCryptor', :git => 'https://github.com/RNCryptor/RNCryptor.git'**
+ set the same line in podfile of our private repo project and it works

**Comment by shshalom** [comment]
So you're saying that both (client and framework) pod files has to have the same line for the "No such module to disappear"?

**Comment by alexs555** [comment]
I confirm that both pod files have the same line, pointing to master branch and we have no any errors

**Comment by shshalom** [comment]
Ok, I'll try that.

**Comment by alexs555** [comment]
also, be sure that all pod's targets in client project has "enable legacy swift version" option turned off

**Comment by shshalom** [comment]
Will do. Thanks.

**Comment by rnapier** [comment]
I thought I pushed this yesterday, but I see there was an auth error. Now pushed:

```
-> RNCryptor (5.0.1)
   Cross-language AES Encryptor/Decryptor data format.
   pod 'RNCryptor', '~> 5.0.1'
   - Homepage: https://github.com/rnapier/RNCryptor
   - Source:   https://github.com/rnapier/RNCryptor.git
   - Versions: 5.0.1, 4.0.0, 4.0.0-beta.1, 3.0.1, 3.0.0, 2.2, 2.1, 2.0, 1.1 [master repo]
```

**Comment by shshalom** [comment]
Thanks @rnapier :-)
@alexs555 it worked :-) 👍
