### ISSUE TITLE
RNCryptor 5 and dropping of ObjC bridging

### ISSUE THREAD

**Issue by chadbag** [RNCryptor/RNCryptor#219]
Do you anticipate that the bridging will return at some point?  Our Objective-C app uses the swift RNCryptor as it is "the future" and seems to have the most work being done on it, etc.

We have other new work being done in Swift as a way to work towards Swift transitions.

Obviously this change affects us.  If we stay at RNCryptor 4 and "legacy swift" everything should work but we limit ourselves to Swift 2.2/2.3 (whatever legacy is).

If you anticipate eventually re-adding Objective0C bridging support then made we deal with it in the meantime and update when that happens.  If you don't anticipate it (when the Swift 3 compiler is more stable) then we'll need to downgrade to the Objective-C code.

**Comment by rnapier** [comment]
I would recommend using the ObjC code. It's fully supported. I anticipate doing an API refresh on it to more closely match the Swift API (I made some API mistakes early in RNCryptor's life that I fixed in the Swift version). It is my intent that the Swift and ObjC versions should be able to live in the same code base without conflict if needed. RNCryptor is pretty small, so I believe two simple implementations is better than one complicated implementation.

I have not abandoned the ObjC version at all. Had to do over again, I would have created a new "RNCryptor-Swift" repository starting at version 1.0 and left the ObjC version here. Hijacking this repository for the Swift implementation was a mistake, but hard to unwind now.

Bridging between Swift and ObjC forces compromises on both that I think are unwarranted in a project this small, so I expect that the two will remain separate for the foreseeable future. ObjC bridging is valuable, but comes at a cost.

Please feel free to open any issues you find in the ObjC code (including feature requests). It is not legacy or abandoned.

**Comment by chadbag** [comment]
OK, thanks.  I did exactly that.  A request when you do look at the ObjC code again is to make synchronous versions of addData: and finish.  I temporarily made addData have a synchronous flag and then async dispatch as is or not using that flag, and made two new routines addData: and synchronousAddData: that default the flag to one or the other.  Also made a synchronousFinish from finish and made the normal finish just dispatch async the new synchronous version.  The need is because we have a subclass of NSInputStream that takes an encrypted source and wraps an normal NSInputStream and in order to read: data and then pass it on the decryption needs to be synchronous.  The Swift version offered this.

**Comment by rnapier** [comment]
Agreed. I made all the calls in Swift synchronous because it's much easier to handle the async yourself when you want it than to get the framework to stop it.

**Comment by chadbag** [comment]
Many thanks.

**Comment by thepoortom** [comment]
It'll be good if RNCryptor-objc will be listed in Cocoapods. It took some time to figure out how to include ObjC version to my project, I use checkout for now:
`pod 'RNCryptor-objc', :git => 'https://github.com/RNCryptor/RNCryptor-objc.git'`
