### ISSUE TITLE
php decryption getting 'Unsupported schema version 197' issue

### ISSUE THREAD

**Issue by dhobaleabhijit** [RNCryptor/RNCryptor#229]
Hello Team,

Thanks for providing us great tool for encryption and decryption. We encrypted file from objective C and try to decrypt that in php. While performing this operation I am getting following error message -
"message":"Unsupported schema version 197"

Will you please help us to resolve this.
Thank in advance.

**Comment by rnapier** [comment]
This means the data you're passing to PHP is not the exact data that ObjC output. In most cases it means you've applied an incorrect encoding somewhere along the way. 197 is a kind of surprising first byte (since it's not a Base64 value), but that's definitely the issue. You've corrupted your data.

Look at the data that is output by ObjC. Look at the data that you're passing to PHP. The two must be byte-for-byte identical.
