### ISSUE TITLE
RNCryptor 5.0.1 - Swift 3 (with Cocoapods) Can't Be Used From Objective C

### ISSUE THREAD

**Issue by kbosselman** [RNCryptor/RNCryptor#230]
It doesn't appear that the Swift version can be used from Objective C.

The generated RNCryptor-Swift.h doesn't contain the RNCryptor class definitions. This greatly limits the usability of this framework.

**Comment by stephenfeather** [comment]
Isn't that why there is another repo (https://github.com/RNCryptor/RNCryptor-objc) mentioned in the description of this repo?

**Comment by kbosselman** [comment]
So I was originally using the ObjC library, but when the switch was made to Swift it appeared the ObjC library had been largely deprecated and was no longer being actively supported (before some commits this September it had been over a year between commits), so I switched to the Swift version.

With the Swift 3 version dropping ObjC compatibility I'm curious if the ObC library is again going to be a first class citizen.

**Comment by rnapier** [comment]
The ObjC version is not deprecated. It's fully supported and will likely have updates in the future. It hasn't been updated in a while mostly because it hasn't needed many changes. I originally wanted the Swift version to be directly usable from ObjC, but this turned out to be very complicated due to some bugs in the Swift compiler, and forced ObjC users to include the Swift runtime (which was bad for everyone). I extracted the ObjC version to its own repository to make it a first-class citizen, not to deprecate it.

**Comment by jifang** [comment]
Is it a generic problem to all libraries written in swift3 or very specific to RNCryptor?

**Comment by rnapier** [comment]
Fairly specific to RNCryptor, but I would expect it in a lot of Swift libraries. Maintaining ObjC compatibility requires a lot of trade-offs and you don't get it for free. Maintaining a separate version for ObjC and one for Swift lets each be the best for the language it's intended for, and you can use both in the same program, so there's not much downside.
