### ISSUE TITLE
Question about usage of SHA-1

### ISSUE THREAD

**Issue by buscarini** [RNCryptor/RNCryptor#237]
Given some recent news (https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html) I'm checking all our company code to see that we are not using SHA-1 for anything critical. I've found an issue that states that the way you are using SHA-1 is not a security issue. Could you please elaborate on this? I've searched for more info on the issue but I haven't been able to find it, and the documentation is too technical for me.

Thanks

**Comment by rnapier** [comment]
Short version: RNCryptor uses SHA-1 as part of PBKDF2. PBKDF2 is responsible for stretching passwords into keys. The main goal of stretching is to be slow and difficult to parallelize. So the only thing I need to prove is that given an input (a password and a salt), there is no shortcut to derive the key faster than running PBKDF2. To achieve that, my hash function needs to be unpredictable, but does not need to be collision resistant. MD5 would be fine for PBKDF2. Any hash whose output is indistinguishable from random (and even MD5 achieves that) is totally fine.

That said, if I were picking my hash with no preconditions, I'd have used used one of the SHA-2 variants (probably SHA-512). Why, when I say it doesn't matter? Hygiene. Using a better algorithm as your default, even when it doesn't matter, means that the lesser algorithm isn't in the system and is harder to accidentally use when it does. But I do have preconditions: existing crypto libraries. Excellent, well-vetted PBKDF2+HMAC+SHA1 implementations are insanely common on many platforms. If I used something else, I'd likely have to write my own PBKDF2 primitive on some platforms, and I avoid writing security primitives if I can help it. It's too easy to mess them up. (This is a current debate around the [v4 protocol](https://github.com/RNCryptor/RNCryptor-Spec/blob/master/draft-RNCryptor-Spec-v4.0.md); I still may switch to SHA-2 there.)

Slightly more technical version: To be secure, PBKDF2 requires some pseudorandom function (a PRF). A PRF has a very specific definition. First, it must be "efficiently computable." Second, if you consider all PRF functions together as a set, and select one of them, then there is no efficient algorithm that could distinguish between the function you selected and a truly random function (usually called a "random oracle"). "Distinguish" has a slightly technical meaning that includes "with significant advantage." Basically, you can't reliably guess more than 50% of the time which is which.

To reiterate the point, though: PBKDF2 requires a PRF. It does not require a hash. It doesn't care about hashes. You could hand any PRF to PBKDF2 and it achieves its security proof. So we just need some PRF.

We use HMAC (when we say "PBKDF2 with SHA-1" we really mean "PBKDF2 with HMAC with SHA-1"). [HMAC has been proven to be a PRF provided its hash's compression function is a PRF.](http://cseweb.ucsd.edu/~mihir/papers/hmac-new.html) (The "compression function" is a piece of a cryptographic hash function, such as SHA-1.) This is a really important finding. Before 2006, it was only known that HMAC was a PRF if the compression function were a PRF *and* the hash function were weakly collision resistant. (The failure of "weakly collision resistant" in SHA-1 is your question.) But since 2006, we've had a solid proof that if the compression function is a PRF, we're good.

Now comes an interesting question. Is the compression function of SHA-1 (Davies-Meyer) a PRF? (We're now at the very edge of my crypto training, so hopefully this part is correct…) Well… I think we actually know it isn't, but it is really close to a PRF and no one has formulated an attack based on the difference. That said, it's kind of irrelevant to your question, since both MD5 and SHA-2 use the same compression function. For practical purposes, we generally treat SHA-1/SHA-2 and their compression function as a PRF. We only question their collision resistance, not their randomness, and their collision resistance is irrelevant to HMAC and thus to PBKDF2.

The real takeaways from this long-winded discussion are:

* SHA1 is totally fine to use in PBKDF2+HMAC. Even MD5 would be fine. If you trust SHA-2 in PKBDF+HMAC, you should trust SHA-1 for the same reasons.
* "Secure" vs "insecure" is based on proofs that cover entire systems, not just individual pieces. Combining "secure" pieces incorrectly can lead to highly insecure systems. Conversely, pieces that have known attacks in one context may be perfectly suitable in another.

**Comment by buscarini** [comment]
Thanks for the detailed explanation! 👍👍👍
