### ISSUE TITLE
App store submission regarding encyption

### ISSUE THREAD

**Issue by benny-innofaith** [RNCryptor/RNCryptor#255]
Are there additional considerations when submitting a app with this library to the app store?

I am assuming including this library counts as encryption and would require me to answer additional questions as stated [here](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SubmittingTheApp.html#//apple_ref/doc/uid/TP40011225-CH33-SW6). Is this correct?

**Comment by rnapier** [comment]
This can only be answered by your attorney. (I used to give advice, and an attorney friend of mine correctly explained to me that my advice is meaningless and harmful, particularly because the regulations are complex, non-obvious, and change.)

Cossack Labs did a helpful write up, and I more or less believe them, but they also aren't lawyers and so their advice is also basically meaningless. Even so, here it is: https://medium.com/@cossacklabs/apple-export-regulations-on-crypto-6306380682e1
