### ISSUE TITLE
RNCryptor not working well on iPhone SE

### ISSUE THREAD

**Issue by vinaychaharg** [RNCryptor/RNCryptor#281]
We are using RNCryptor to encrypt API data in our iOS app, the data gets decrypted on the server. This works well for all the devices except **iPhone SE**.

The PHP server is not able to decrypt the data sent by **iPhone SE**, for all other devices it is just perfect.

The code is same for all the devices so I doubt the issue is related to this particular device, but we cannot remove support for this device right now. Please help.

Any help is appreciated.

**Comment by rnapier** [comment]
This is a very interesting problem. Have you seen this on multiple SE devices or just one? Is it across a range of OS versions? Do you have an example of the output from an SE device? How are you sending the data to the server?

**Comment by vinaychaharg** [comment]
Yes I tried it on quite some devices and it worked on 
iPhone 6
iPhone 6S
iPhone 7
iPhone 8 and
iPhone X

But when I tried it on one iPhone SE it did not work, so I tried on another SE and it failed there too.

When we try to decrypt the data on server which is sent by iPhone SE device it returns "false" for other devices it returned valid JSON.
This is probably because RNCryptor was not able to decrypt the data sent by iPhone SE device. 

FYI: The OS on both the SE devices was iOS 12.0

Let me know if this helps.

Thanks

**Comment by utiko** [comment]
@vinaychaharg did you handle the issue with SE, is it really a case?

**Comment by rnapier** [comment]
I have never seen an example of this. I suspect the problem is decrypting something too large and running out of memory. I would be happy to look at an actual example, but RNCryptor definitely works on iPhone SE.

RNCryptor never returns “false” or JSON, it only returns Data or throws and error, so it is possible this is a bug in whatever calling code is wrapping it. 

If someone has an actual example of this, I’m happy to reopen this case and look at it further.
