### ISSUE TITLE
how i can install RNCryptor in my MacoS app

### ISSUE THREAD

**Issue by zeroDevOne** [RNCryptor/RNCryptor#293]
can i confirm my closed question? 

i have MacOSX 10.13.6 (i don't want to upgrade to 10.15 macos because it freezing my Computer) that i need to buy a new computer. 

i have installed xcode 10.1 (latest version for this platform)  

i want to make my home made app for my self, i'm not  pro dev, just newbie. 

is it possible to install old version of RNCryptor because its just for home not prod. 

i try to install via pod install ->  pod 'RNCryptor', '~> 5.0' but in xcode 10.1 it says that it not support swift 5.0 syntax. i try to use xcode 8.2.1 but gives much errors so i can't fix them. 

if it not possible to install it in this version of xcode 10.1 and macos 10.3.6 i will try to find another library for it. Can you please answer me or confirm that it not supported

**Comment by rnapier** [comment]
`pod 'RNCryptor', '~> 5.0'` will pull in version 5.1 (because `~> 5.0` means "up to version 6"). You need `~> 5.0.0`. Verify when when you `pod install` that it installs the version you want (5.0.3).

(You don't need to create a new issue here. If you comment on closed issues, it still works and I can reopen it. "Closed" just means that I believe it is done; it doesn't lock the issue.)

**Comment by zeroDevOne** [comment]
> `pod 'RNCryptor', '~> 5.0'` will pull in version 5.1 (because `~> 5.0` means "up to version 6"). You need `~> 5.0.0`. Verify when when you `pod install` that it installs the version you want (5.0.3).
> 
> (You don't need to create a new issue here. If you comment on closed issues, it still works and I can reopen it. "Closed" just means that I believe it is done; it doesn't lock the issue.)

thanx for your reply, i'll try and that's work, right now i can do my app.
