### ISSUE TITLE
Security threat due to insecure function "memcpy" in RNCryptor.m class

### ISSUE THREAD

**Issue by Priya1794** [RNCryptor/RNCryptor#294]
Hi,

I am getting security threat in below code for RNCryptor.m class

https://github.com/RNCryptor/RNCryptor-objc/blob/master/RNCryptor/RNCryptor.m

There are 4 occurrences of "memcpy()" function which is an insecure function acc to security tool.

In **static int
RN_CCKeyDerivationPBKDF( CCPBKDFAlgorithm algorithm, const char *password, size_t passwordLen,
                     const uint8_t *salt, size_t saltLen,
                     CCPseudoRandomAlgorithm prf, uint rounds,
                     uint8_t *derivedKey, size_t derivedKeyLen)**, there are 4 occurences-

memcpy(saltCopy, salt, saltLen);
memcpy(collector, oldbuffer, hlen);	
memcpy(oldbuffer, newbuffer, hlen);
memcpy(derivedKey+offset, collector, copyLen);

Below is the issue description and reference links from security team.

**Issue description :** Use of insecure functions/potential dangerous functions
**Reference link:** https://cwe.mitre.org/data/definitions/676.html
This would explain why **SECURITY TEAM** is recommending the change of these functions.

Please provide solution for this as soon as possible as it is very urgent.

Thanks and Regards,
Priya Mehndiratta

**Comment by Priya1794** [comment]
They provided this link too 
CWE-789 - Uncontrolled Memory Allocation. Please refer this.

and provide solution.

**Comment by rnapier** [comment]
CWE-789 also does not apply to memcpy. In this context, it refers to your program accepting arbitrarily large passwords from the user, not to the hashing function. You would need to limit password length in the UI to reasonable lengths to address CWE-789. RNCryptor intentionally doesn’t (and shouldn’t) limit password length. 

Since you’ve indicated this is urgent, please let me know if you’re looking for consulting services and I can provide my rates. I can evaluate the report you’ve received and help you address your security concerns. But the CWEs you’ve sent don’t apply to memcpy or RNCryptor.

Note that the code you’re referencing is only used if you’re building for OS X 10.6. If this is an iOS app or a macOS app targeting later versions, it isn’t used.

As always, if there is a particular change you have in mind to address your needs, I’m happy to look at a PR, or to develop a custom version of RNCryptor on a consulting basis. Best of luck.
