### ISSUE TITLE
Documentation - Explanations

### ISSUE THREAD

**Issue by rnapier** [RNCryptor/RNCryptor#3]

**Comment by Gavintc** [comment]
Hi rnapier, thanks for your library. Since part of my project is written in Java, I need to decrypt those stuff generated from Java. Output from Java is a salt, IV, cipher text and password. I have successfully get the encryption key using keyForPassword in your library, but what's next? Since your decryption API needs a HMACKey, I still don't know where to get it after going through all the header files. Encryption in Java is using AEC/CBC/ZeroBytePadding. Thanks.

**Comment by rnapier** [comment]
See JNCryptor for a Java implementation of the RNCryptor encryption format. https://github.com/RNCryptor/JNCryptor
