### ISSUE TITLE
PBKDF2 SHA1 iterations

### ISSUE THREAD

**Issue by Masrepus** [RNCryptor/RNCryptor#310]
I saw that the V3 format is using SHA1 with 10,000 iterations for key derivation, which is rather far away from the current [recommendation](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2) of 1,300,000 iterations. I read in your FAQs that the decision to hardcode the iterations is intentional to make the format interoperable, but since RNCryptor's pbkdf2 functionality is still used by apps in the app store, I'm wondering what the best approach would be to prevent these apps from relying on such a low iteration count.

**Comment by rnapier** [comment]
There is no way to change the encryption used by existing apps. That would be true no matter the format. But in particular, the [RNCryptor v3 format](https://github.com/RNCryptor/RNCryptor-Spec/blob/master/RNCryptor-Spec-v3.md) does not encode an iteration count, so it absolutely cannot be changed for existing programs. And no system can change the parameters for existing encrypted data without modifying the file, even systems that do encode their parameters.

[RNCryptor v4](https://github.com/RNCryptor/RNCryptor-Spec/blob/master/draft-RNCryptor-Spec-v4.0.md) supports encoding the iteration count up to 10M iterations. That format has never been implemented to my knowledge. I wouldn't implement the v4 spec today; it's not worth the trouble. Widely available crypto libraries have improved a lot since I designed it, and so some of the trade-offs are no longer necessary.

Any app that uses RNCryptor v3 today can definitely alter the number of iterations for its own ecosystem by modifying the code. It's a simple change for every RNCryptor implementation. This will break compatibility of course, both with other implementations and with any existing encrypted data, but most uses of RNCryptor are within a single ecosystem; it's not generally treated as a general-purpose storage format like ZIP. Modifying the iteration count has been commonly done for JavaScript implementations, which were (at the time) unable to handle 10k iterations in reasonable time and often were forced to use only 1000 to keep the system usable.
