### ISSUE TITLE
String encrypted on iOS can not decrypt on PHP

### ISSUE THREAD

**Issue by anhhtz** [RNCryptor/RNCryptor#83]
Hi,

I encrypt the string on iOS with the code below:
# import "RNEncryptor.h"
# import "RNDecryptor.h"
# import "Base64.h"

NSString\* plainString = @"Hello";
NSString\* serectKey = @"serectKEY";
NSString\* encryptedString;

```
NSError *error = nil;

NSData *data = [plainString dataUsingEncoding:NSUTF8StringEncoding];

NSData *encryptedData = [RNEncryptor encryptData:data
                                    withSettings:kRNCryptorAES256Settings
                                        password:serectKey
                                           error:&error];

encryptedString = [[NSString alloc] initWithData:encryptedData
                                        encoding:[NSString defaultCStringEncoding]];


encryptedString = [encryptedString base64EncodedString];
```

The encryptString can not be decrypt with the PHP code:

<?php

require_once **DIR** . '/../RNDecryptor.php';

$password = //serectKey here;
$base64Encrypted = //encryptedString here
$cryptor = new RNDecryptor();
$plaintext = $cryptor->decrypt($base64Encrypted, $password);

echo "Plaintext: $plaintext\n";
echo "\n";

?>

Sorry if this is a newbie question. I am newbie in encryption !

Thanks !

**Comment by startupthekid** [comment]
Since this issue is still open, I'd like to add my voice to it as well (although I'm using NodeJS not PHP).

I believe the issue everyone else is talking about is when we use `RNEncryptor` to encrypt some `NSString` instance to an `NSData` instance and then subsequently send that data object to the server, what's sent to the server is NOT the encrypted string but rather the `description` method output of the `NSData` class.

For example, if I send my encrypted data to my backend and print out the data, I get:

`<03011103 89d76a9d 108982f8 bca3deb3 64b64592 9a2db47b 89fbcd43 89474672 308d9b05 b5af0b71 aa17d166 0b43279e 8fefc58a 43868e4d beb5d03b cbb79f28 ea3c411c f53332b8 076f63f7 a7f6b444 032e>`

which is the same output I get in Xcode by calling `[data description];` This is not the behavior I expected, I expected the server to receive the encrypted string itself, although it does make sense as to why it happens. All the networking libraries know is they have to send over the data and for some reason they decide to send the `description` output of `NSData`. Having a method on `RNEncryptor` that returns an encrypted string, not a data object, would be massively helpful. For now, base64 encoding on client side and sending it over to the server will have to do.

**Comment by rnapier** [comment]
You're correct that's the output of -description. I don't know of any networking library that transparently calls -description on data it is passed. If there is such a library, it's broken and should be fixed. I suspect this is actually a bug in the client code, not the networking library. 

There is no such thing as an "encrypted string" in the way you mean. There are just various string encodings of encrypted data. One of those encodings is base64. Another popular one is hex encoding (which is used heavily in the RNCryptor tests). There are uuencoding and yEnc. Some people need a full MIME body. iOS's base64 encoder offers several formatting options that callers may want to use. Many uses do not require string encoding at all. 

Rather than force one formatting of base64 on the caller, RNCryptor returns data that you may format any way you like. 

Since the addition of an easy to use base64EncodedStringWithOptions: method, there has been no reason to add base64 to RNCryptor even as a convenience.

**Comment by startupthekid** [comment]
Right yeah it makes complete sense as to why any server side implementation receives that output. And I misspoke, when I say encrypted string I mean some encoding representation of the encrypted `NSData` object, and base64 was exactly what I was looking for. 

Love this library by the way, it's a life saver.

**Comment by long-nguyen** [comment]
encryptedString =   [encryptedData base64EncodedStringWithOptions:0]; is working OK
